### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by berenddeboer** [klazuka/example-elm-hot-webpack#2] opened 2019-04-23 02:09 UTC
Get this when I try to install it:

```
 npm install

> elm@0.19.0 install /home/berend/src/example-elm-hot-webpack/node_modules/elm
> binwrap-install

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/berend/src/example-elm-hot-webpack/node_modules/natives/index.js:137:5)
    at require (/home/berend/src/example-elm-hot-webpack/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/berend/src/example-elm-hot-webpack/node_modules/natives/index.js:137:5)
    at require (/home/berend/src/example-elm-hot-webpack/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/berend/src/example-elm-hot-webpack/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/berend/src/example-elm-hot-webpack/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/berend/src/example-elm-hot-webpack/node_modules/unzip/node_modules/graceful-fs/fs.js:1:99)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.0 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm@0.19.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/berend/.npm/_logs/2019-04-23T02_06_46_466Z-debug.log
```

Versions:
```
> nodejs --version
v10.15.2
> npm --version
6.4.1
```

**Comment by berenddeboer** [comment] 2019-04-23 02:23
OK, I did a:

```
npm install elm@0.19
npm install
```

and that seems to have worked. Haven't tried but perhaps the entire error message could have been ignored? Anyway, it's working now.

**Comment by klazuka** [comment] 2019-05-03 17:01
This `ReferenceError: internalBinding is not defined` is some kind of version incompatibility in the upstream dependencies. The problem is with `binwrap` and `natives`, which the Elm compiler depends on. So they need to update their dependencies (assuming that a fix has been published).

**Closed as completed by klazuka** 2019-05-03 17:01 UTC
